// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/atreya2011/grpc-practice/postgres-crud/postgrescrud/postgrescrud.proto

package postgrescrud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: gorm:"not null"
	FirstName  string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty" gorm:"not null"`
	MiddleName string `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// @inject_tag: gorm:"not null"
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty" gorm:"not null"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" sql:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreatePersonRequest struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" sql:"-"`
}

func (m *CreatePersonRequest) Reset()         { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()    {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{1}
}

func (m *CreatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonRequest.Unmarshal(m, b)
}
func (m *CreatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonRequest.Marshal(b, m, deterministic)
}
func (m *CreatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonRequest.Merge(m, src)
}
func (m *CreatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePersonRequest.Size(m)
}
func (m *CreatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonRequest proto.InternalMessageInfo

func (m *CreatePersonRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type CreatePersonResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" sql:"-"`
}

func (m *CreatePersonResponse) Reset()         { *m = CreatePersonResponse{} }
func (m *CreatePersonResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePersonResponse) ProtoMessage()    {}
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{2}
}

func (m *CreatePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonResponse.Unmarshal(m, b)
}
func (m *CreatePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonResponse.Marshal(b, m, deterministic)
}
func (m *CreatePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonResponse.Merge(m, src)
}
func (m *CreatePersonResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePersonResponse.Size(m)
}
func (m *CreatePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonResponse proto.InternalMessageInfo

func (m *CreatePersonResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadPersonRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" sql:"-"`
}

func (m *ReadPersonRequest) Reset()         { *m = ReadPersonRequest{} }
func (m *ReadPersonRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPersonRequest) ProtoMessage()    {}
func (*ReadPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{3}
}

func (m *ReadPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPersonRequest.Unmarshal(m, b)
}
func (m *ReadPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPersonRequest.Marshal(b, m, deterministic)
}
func (m *ReadPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPersonRequest.Merge(m, src)
}
func (m *ReadPersonRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPersonRequest.Size(m)
}
func (m *ReadPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPersonRequest proto.InternalMessageInfo

func (m *ReadPersonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadPersonResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" sql:"-"`
}

func (m *ReadPersonResponse) Reset()         { *m = ReadPersonResponse{} }
func (m *ReadPersonResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPersonResponse) ProtoMessage()    {}
func (*ReadPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{4}
}

func (m *ReadPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPersonResponse.Unmarshal(m, b)
}
func (m *ReadPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPersonResponse.Marshal(b, m, deterministic)
}
func (m *ReadPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPersonResponse.Merge(m, src)
}
func (m *ReadPersonResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPersonResponse.Size(m)
}
func (m *ReadPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPersonResponse proto.InternalMessageInfo

func (m *ReadPersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type ListPeopleResponse struct {
	Peoples              []*Person `protobuf:"bytes,1,rep,name=peoples,proto3" json:"peoples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" gorm:"-" sql:"-"`
	XXX_unrecognized     []byte    `json:"-" gorm:"-" sql:"-"`
	XXX_sizecache        int32     `json:"-" gorm:"-" sql:"-"`
}

func (m *ListPeopleResponse) Reset()         { *m = ListPeopleResponse{} }
func (m *ListPeopleResponse) String() string { return proto.CompactTextString(m) }
func (*ListPeopleResponse) ProtoMessage()    {}
func (*ListPeopleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c810cd659e67dac, []int{5}
}

func (m *ListPeopleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPeopleResponse.Unmarshal(m, b)
}
func (m *ListPeopleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPeopleResponse.Marshal(b, m, deterministic)
}
func (m *ListPeopleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPeopleResponse.Merge(m, src)
}
func (m *ListPeopleResponse) XXX_Size() int {
	return xxx_messageInfo_ListPeopleResponse.Size(m)
}
func (m *ListPeopleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPeopleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPeopleResponse proto.InternalMessageInfo

func (m *ListPeopleResponse) GetPeoples() []*Person {
	if m != nil {
		return m.Peoples
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "postgrescrud.Person")
	proto.RegisterType((*CreatePersonRequest)(nil), "postgrescrud.CreatePersonRequest")
	proto.RegisterType((*CreatePersonResponse)(nil), "postgrescrud.CreatePersonResponse")
	proto.RegisterType((*ReadPersonRequest)(nil), "postgrescrud.ReadPersonRequest")
	proto.RegisterType((*ReadPersonResponse)(nil), "postgrescrud.ReadPersonResponse")
	proto.RegisterType((*ListPeopleResponse)(nil), "postgrescrud.ListPeopleResponse")
}

func init() {
	proto.RegisterFile("github.com/atreya2011/grpc-practice/postgres-crud/postgrescrud/postgrescrud.proto", fileDescriptor_8c810cd659e67dac)
}

var fileDescriptor_8c810cd659e67dac = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xb3, 0x52, 0xe8, 0xdd, 0x84, 0xc0, 0x94, 0x51, 0x65, 0x9b, 0x16, 0x8c, 0x84, 0xf6,
	0xc0, 0x62, 0x5a, 0xde, 0x78, 0xa4, 0xf0, 0x86, 0x50, 0xe9, 0x07, 0x80, 0xdc, 0xf8, 0x2e, 0x58,
	0x4a, 0x62, 0xcf, 0x76, 0x90, 0x26, 0xc4, 0x0b, 0xbf, 0xc0, 0x67, 0xf1, 0xc8, 0x2f, 0xf0, 0x21,
	0x28, 0x76, 0x3a, 0x2d, 0x09, 0x20, 0xf1, 0xe8, 0x73, 0x8e, 0xcf, 0xb9, 0xc7, 0xbe, 0xf0, 0x3e,
	0x97, 0xae, 0xe0, 0xdb, 0x34, 0x53, 0x25, 0xe3, 0xce, 0xe0, 0x15, 0x5f, 0x3e, 0x5f, 0x2c, 0x58,
	0x6e, 0x74, 0x76, 0xae, 0x0d, 0xcf, 0x9c, 0xcc, 0x90, 0x69, 0x65, 0x5d, 0x6e, 0xd0, 0x9e, 0x67,
	0xa6, 0x16, 0xd7, 0xa7, 0xc1, 0x21, 0xd5, 0x46, 0x39, 0x45, 0x0e, 0x6e, 0x62, 0xf1, 0x71, 0xae,
	0x54, 0x5e, 0x20, 0xe3, 0x5a, 0x32, 0x5e, 0x55, 0xca, 0x71, 0x27, 0x55, 0x65, 0x83, 0x36, 0x3e,
	0x6a, 0x59, 0x7f, 0xda, 0xd6, 0x17, 0xec, 0x4d, 0xa9, 0xdd, 0x55, 0x20, 0x69, 0x0d, 0x93, 0x35,
	0x1a, 0xab, 0x2a, 0x72, 0x17, 0x22, 0x29, 0xe6, 0xa3, 0x64, 0x74, 0x76, 0x6b, 0x13, 0x49, 0x41,
	0x4e, 0x00, 0x2e, 0xa4, 0xb1, 0xee, 0x63, 0xc5, 0x4b, 0x9c, 0x47, 0xc9, 0xe8, 0x6c, 0xba, 0x99,
	0x7a, 0xe4, 0x1d, 0x2f, 0x91, 0x9c, 0xc2, 0x7e, 0x29, 0x85, 0x28, 0x30, 0xf0, 0x7b, 0x9e, 0x87,
	0x00, 0x79, 0xc1, 0x11, 0x4c, 0x0b, 0xbe, 0xbb, 0x3e, 0xf6, 0xf4, 0x9d, 0x06, 0x68, 0x48, 0xba,
	0x82, 0x07, 0x2b, 0x83, 0xdc, 0x61, 0x08, 0xdf, 0xe0, 0x65, 0x8d, 0xd6, 0x91, 0x67, 0x30, 0xd1,
	0x1e, 0xf0, 0x73, 0xec, 0x2f, 0x67, 0x69, 0xa7, 0x7b, 0x2b, 0x6e, 0x35, 0xf4, 0x29, 0xcc, 0xba,
	0x26, 0x56, 0xab, 0xca, 0x62, 0xbf, 0x09, 0x7d, 0x02, 0xf7, 0x37, 0xc8, 0x45, 0x37, 0xaa, 0x2f,
	0x7a, 0x05, 0xe4, 0xa6, 0xa8, 0xb5, 0xfa, 0xbf, 0x81, 0x5e, 0x03, 0x79, 0x2b, 0xad, 0x5b, 0xa3,
	0xd2, 0x05, 0x5e, 0x7b, 0xa4, 0x70, 0x5b, 0x7b, 0xc4, 0xce, 0x47, 0xc9, 0xde, 0x5f, 0x4d, 0x76,
	0xa2, 0xe5, 0x8f, 0x08, 0x0e, 0xd6, 0xad, 0x60, 0x65, 0x6a, 0x41, 0x2e, 0x61, 0x12, 0x7a, 0x92,
	0xc7, 0xdd, 0x9b, 0x7f, 0x78, 0xc2, 0x98, 0xfe, 0x4b, 0x12, 0x26, 0xa2, 0xc9, 0xb7, 0x9f, 0xbf,
	0xbe, 0x47, 0x31, 0xbd, 0xc7, 0x3e, 0x2f, 0x3a, 0xdb, 0xf5, 0xb2, 0x6d, 0x42, 0x3e, 0xc0, 0xb8,
	0x69, 0x42, 0x0e, 0xd3, 0xb0, 0x3c, 0xe9, 0x6e, 0x79, 0x52, 0xbf, 0x3c, 0x71, 0xd2, 0x4d, 0x19,
	0xb6, 0xa6, 0xc7, 0x3e, 0xe3, 0x90, 0xcc, 0xfa, 0x19, 0x8c, 0x17, 0x05, 0xf9, 0x04, 0xe3, 0xe6,
	0xb5, 0xc9, 0x69, 0xd7, 0x67, 0xf0, 0x4d, 0xfd, 0xa0, 0xe1, 0x17, 0xd1, 0x13, 0x1f, 0xf4, 0x88,
	0x3c, 0x1c, 0x04, 0x7d, 0x91, 0xe2, 0xeb, 0x76, 0xe2, 0x27, 0x7f, 0xf1, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0x1e, 0x7c, 0x60, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostgresCrudClient is the client API for PostgresCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostgresCrudClient interface {
	Create(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPeopleResponse, error)
	Read(ctx context.Context, in *ReadPersonRequest, opts ...grpc.CallOption) (*ReadPersonResponse, error)
}

type postgresCrudClient struct {
	cc *grpc.ClientConn
}

func NewPostgresCrudClient(cc *grpc.ClientConn) PostgresCrudClient {
	return &postgresCrudClient{cc}
}

func (c *postgresCrudClient) Create(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := c.cc.Invoke(ctx, "/postgrescrud.PostgresCrud/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgresCrudClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPeopleResponse, error) {
	out := new(ListPeopleResponse)
	err := c.cc.Invoke(ctx, "/postgrescrud.PostgresCrud/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgresCrudClient) Read(ctx context.Context, in *ReadPersonRequest, opts ...grpc.CallOption) (*ReadPersonResponse, error) {
	out := new(ReadPersonResponse)
	err := c.cc.Invoke(ctx, "/postgrescrud.PostgresCrud/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostgresCrudServer is the server API for PostgresCrud service.
type PostgresCrudServer interface {
	Create(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	List(context.Context, *empty.Empty) (*ListPeopleResponse, error)
	Read(context.Context, *ReadPersonRequest) (*ReadPersonResponse, error)
}

func RegisterPostgresCrudServer(s *grpc.Server, srv PostgresCrudServer) {
	s.RegisterService(&_PostgresCrud_serviceDesc, srv)
}

func _PostgresCrud_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresCrudServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgrescrud.PostgresCrud/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresCrudServer).Create(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgresCrud_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresCrudServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgrescrud.PostgresCrud/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresCrudServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgresCrud_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresCrudServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgrescrud.PostgresCrud/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresCrudServer).Read(ctx, req.(*ReadPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostgresCrud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postgrescrud.PostgresCrud",
	HandlerType: (*PostgresCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PostgresCrud_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PostgresCrud_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _PostgresCrud_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/atreya2011/grpc-practice/postgres-crud/postgrescrud/postgrescrud.proto",
}
